### ISSUE TITLE
对框架的一点疑问

### ISSUE THREAD

**Issue by zhangkevd** [KunMinX/android-viabus-architecture#1]
感觉像变种的handler,时间长了或者是业务很多，result里面会不堪重负，且查代码不方便，还不如直接使用Rxjava。

**Comment by KunMinX** [comment]
@zhangkevd 没错，UI逻辑的处理有点像handlerMessages。你想象一下，如果直接在rxjava中回调处理ui逻辑，那么等于业务的工作也在ui层处理了，那么是不是说，我因为需要依赖业务，而需要等业务写完才能写UI，这样就造成了耦合。
