### ISSUE TITLE
Failed to resolve: com.kunminx.viabus:viabus-core:0.4.5

### ISSUE THREAD

**Issue by kakarrot** [KunMinX/android-viabus-architecture#5]
jcenter(), maven()
设置代理，直连都load 不下来。。。

**Comment by KunMinX** [comment]
@kakarrot 稍等几天😂 ，近两周jcenter网络不太稳，平均10次上传只有1次成功。建议先通过demo跑一跑 看一看 玩一玩

**Comment by KunMinX** [comment]
@kakarrot 可以了
