### ISSUE TITLE
demo运行中会崩啊

### ISSUE THREAD

**Issue by houxiaogg** [KunMinX/android-viabus-architecture#7]

**Comment by KunMinX** [comment]
@houxiaogg 我只说一遍：请换位思考一下，你觉得站在对方的视角，看到“demo运行中会崩啊”，会有什么反应吗？—— 当然是诧异啊，无凭无据啊。请尝试自行解决，或者至少，请粘贴崩溃信息，不然我怎么会知道遇到什么问题了呢？

**Comment by KunMinX** [comment]
已解决了，recycleview自身的bug
